/*
  # Update transcription queue structure for single page processing

  1. Table Changes
    - Drop existing transcription_queue table
    - Create new structure with single page_number column
    - Recreate indexes and policies

  2. Security
    - Maintain existing RLS policies
    - Keep service_role full access
*/

-- Drop existing table and recreate with new structure
DROP TABLE IF EXISTS public.transcription_queue CASCADE;

-- Create new transcription_queue table for single page processing
CREATE TABLE public.transcription_queue (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  processo_id uuid NOT NULL REFERENCES public.processos(id) ON DELETE CASCADE,
  page_number integer NOT NULL CHECK (page_number > 0),
  status text DEFAULT 'pending'::text NOT NULL CHECK (status IN ('pending', 'processing', 'completed', 'error')),
  created_at timestamptz DEFAULT now() NOT NULL
);

-- Enable RLS
ALTER TABLE public.transcription_queue ENABLE ROW LEVEL SECURITY;

-- Recreate policies
CREATE POLICY "Allow service_role to manage queue"
  ON public.transcription_queue
  FOR ALL
  TO service_role
  USING (true);

CREATE POLICY "Allow anon to read queue status"
  ON public.transcription_queue
  FOR SELECT
  TO anon
  USING (true);

-- Recreate indexes
CREATE INDEX idx_transcription_queue_status_created 
  ON public.transcription_queue(status, created_at) 
  WHERE status = 'pending';

CREATE INDEX idx_transcription_queue_processo_status 
  ON public.transcription_queue(processo_id, status);

-- Update get_next_queue_item function for new structure
CREATE OR REPLACE FUNCTION get_next_queue_item()
RETURNS TABLE (
    id bigint,
    processo_id uuid,
    page_number integer,
    file_path text,
    file_url text
) AS $$
BEGIN
    RETURN QUERY
    UPDATE transcription_queue 
    SET status = 'processing' 
    WHERE transcription_queue.id = (
        SELECT q.id 
        FROM transcription_queue q
        JOIN processos p ON q.processo_id = p.id
        WHERE q.status = 'pending'
        ORDER BY q.created_at 
        LIMIT 1
        FOR UPDATE SKIP LOCKED
    )
    RETURNING 
        transcription_queue.id,
        transcription_queue.processo_id,
        transcription_queue.page_number,
        (SELECT p.file_path FROM processos p WHERE p.id = transcription_queue.processo_id),
        (SELECT p.file_url FROM processos p WHERE p.id = transcription_queue.processo_id);
END;
$$ LANGUAGE plpgsql;